-- Create the orders table

CREATE OR REPLACE TABLE CUSTOMER_ORDERS (
  CUSTOMER_ID  NUMBER,
  ORDER_ID     NUMBER,
  ORDER_DATE   DATE,
  ORDER_VALUE  NUMBER(10,2),
  PRODUCT_ID   NUMBER
);
