SELECT
    CUSTOMER_ID,
    PURCHASE_COUNT,
    AVG_ORDER_VALUE,
    HIGH_VALUE_MODEL!PREDICT(
        INPUT_DATA => OBJECT_CONSTRUCT(
            'PURCHASE_COUNT', PURCHASE_COUNT,
            'AVG_ORDER_VALUE', AVG_ORDER_VALUE
        )
    ):PREDICTION:"class"::NUMBER AS PREDICTED_HIGH_VALUE
FROM CUSTOMER_SEGMENTS
ORDER BY PREDICTED_HIGH_VALUE DESC, PURCHASE_COUNT DESC;